version: "3.9"

services:
  db:
    image: postgres:16
    container_name: medcost_db
    environment:
      POSTGRES_DB: medcost_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: medcost_app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/medcost_db
    ports:
      - "8501:8501"
    depends_on:
      - db